var num1=10,num2=20;
console.log(`the numbers after swapping  num1=${num1} and num2=${num2}`);
// var temp;
// temp=num1;
// num1=num2;
// num2=temp;
num1=num1+num2;
num2=num1-num2;
num1=num1-num2;
console.log(`the numbers after swapping num1=${num1} and num2=${num2}`);